### ISSUE TITLE
Robertify has muted itself

### ISSUE THREAD

**Issue by wizard04wsu** [bombies/Robertify-Bot#201]
When I joined the voice channel today, the bot joined as well, but it has somehow muted itself.

![image](https://user-images.githubusercontent.com/695638/232320665-064520fa-eaa5-40e9-b7f8-e5db8b79f438.png)

I made sure I could hear someone else, made sure it was playing something, changed the volume, and disconnected/reconnected it.

**Comment by bombies** [comment]
Ensure the bot has permission to speak in the voice channel.

[Example](https://i.imgur.com/itg3xUn.gif)

**Comment by wizard04wsu** [comment]
Thanks!
