### ISSUE TITLE
Robertify fails to add track to queue

### ISSUE THREAD

**Issue by 321nick** [bombies/Robertify-Bot#312]
When i try to add a track to the queue (via any command, local file or online url) , it will say "6Adding to queue" but then the queue will still be empty and nothing will be playing. 

Heres what it looks like: 
![image](https://github.com/bombies/Robertify-Bot/assets/19196462/d7eadedc-990e-428b-a2c6-ee411393f32a)

i dont know if Robertify has any debug logs or anything i can post to help troubleshoot this. if there is any, please tell me.

**Comment by bombies** [comment]
Should be fixed now.
